language: ruby
rvm:
- 2.2.4
script:
- bundle exec rspec -fd spec/
- bundle exec rake konacha:run
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
deploy:
  provider: heroku
  api_key:
    secure: z3HY2BIa19blrNoh+zns1WeeRAioZW7vmgwv2p7aKBUhjOOxVuJQNfupZ3m8TsqMi3pHKuE7ZzgKnmX79NT665TN/898mJdnIvGPkKhnsDls3F7USa3KQlJry5DwNz5DgAwSwzdbxevjTGd1ttJQcyMHReRNc6Dj2jxAatkJj5fo9lDFQddE40yJsV0mGAsnIV1NZlByProw5JpD3rRrOIKxLJW1MHB74Tjt4ryiH16qv0eNMeO+3de6ZZViy/rX8EsBqjlaiKb64gk+6sFzuNrG+1RbxZ8mJzKAYu4LFCW6Mh+U1kVFuXMbWwFezSCjmZPsuI5aiXJERRKuWPRgGUzlYKoaiEtWlaDGtvuRUMwmqoeZV0qmLDj0DY845Q6c54dDaTcc5UpfMTeYVrb9lBIocV+rXR1NjP42RPWAnijQyN9bC0/A619uyR6APCSwFbBke7oE2aXg0U0vz5RpYylBYCDs3DnmU/vJ5yc+hHYYSsDLkoNUin9PT1vj2bQJ0app0SPWSr5VEvZDKWlXvGxbQ97fR07OPkyH08T4jVEuaRcRQTmh+Mgmq8OzlLFsnrXbrlCojnQh4NYk9gVNk7Bjv8P8aMHoIPBQgkxA2eAAgZxUjv/5cmgFB9V2u/PiPmshA6xqcAf1S48z+2uMPYfkSH5DBv9RcsLwbJcVIrM=
  app: dps-ex3
  on:
    repo: makeus/DSP-Ex3
